Develop
kxkfkqk/taipei-day-trip-website pull request #1
Opened 2021-05-15 07:09 UTC by kxkfkqk

姓名:葉忠翰

網址:http://13.231.74.51:3000/

2021-05-15 15:36 UTC, cwpeng requested changes
功能沒問題，但視窗請找到有效置中的方式，你現在的處理只有在特定幾個解析度會置中，其他常見的螢幕解析度都無法順利置中，例如以下這個 1280 寬的截圖。

![13 231 74 51_3000_](https://user-images.githubusercontent.com/6104683/118369543-5b0adf00-b5d6-11eb-9966-466f9c5e0faf.png)

2021-05-16 06:43 UTC, kxkfkqk commented
已修正,再麻煩確認 謝謝

2021-05-16 10:25 UTC, cwpeng commented
看起來是沒問題，但請重新發 Review Request 給我 ~

2021-05-16 10:28 UTC, cwpeng approved these changes
OK.

2021-05-16 10:30 UTC, merged