Develop
kxkfkqk/taipei-day-trip-website pull request #11
Opened 2021-05-06 08:49 UTC by kxkfkqk

網址:http://13.231.74.51:3000/

老師,我把第二跟第三周的進度混在一起做了,可以一起幫我看嗎

還有我發現真正上線後,圖片載入速度慢很多,
導致卷軸稍微拉快就很容易bug,我自己在主機測試圖片載入很順,
所以就不會出現這個問題,是不是不能用setinterval來做每秒出發呢?
想說先請老師幫我看看其他功能

2021-05-06 14:47 UTC, cwpeng requested changes
進度混在一起我沒有意見哦，不過你的網站現在一打開就看不到資料，請恢復後再和我說 ~

2021-05-06 15:15 UTC, kxkfkqk commented
老師我開起來了
我再想一下怎麼解決圖片載太慢時會有的bug

2021-05-06 15:28 UTC, cwpeng commented
你的網頁打開的第一時間就會大量載入第一頁，你可以透過開發人員工具的 Network 這邊去檢查如下：
![未命名-2](https://user-images.githubusercontent.com/6104683/117324089-0ecaeb00-aec2-11eb-9643-ebe1f09df3cc.png)

我看了你的程式，在觀念上需要很大的調整，你必須仔細的理解每個動作，例如 setInterval 是怎麼運行的應該都有些沒有掌握好，一點點細節的差異就會導致你程式寫不出來，這些可能不是一時片刻能夠改完的，所以我建議你先把第三週的版面處理好，第二週載入動作晚點再回來處理。

第三週的功能沒問題，版面有以下細節問題請你先修正：
1. 選擇日期的輸入框請加上些許 Padding，會比較好看。
2. 手機版面上方的臺北一日遊標題會往下掉，影響到其他視覺，請保持標題只有一行。
3. 手機版面，景點標題和訂購導覽的灰色區塊，版面利用率太低，灰色區塊的 Padding 消失，文字整個靠在邊上，請處理這些細節。我看到的手機版面截圖如下：
![13 231 74 51_3000_attraction_3](https://user-images.githubusercontent.com/6104683/117324720-a2042080-aec2-11eb-9035-5dfb5e0e2404.png)

2021-05-06 15:40 UTC, kxkfkqk commented
了解,我先處理版面問題

2021-05-07 06:44 UTC, kxkfkqk commented
老師,我已經重新上線了
我了解為什麼載入12次頁面,重新調整後變得比較乾淨一些

setinterval據我的了解,它是看你設定多少時間,就多少時間執行一次function
我覺得這方法比直接設定scroll事件還要好,因為使用者拉到最下面,最慢頂多一秒後才載入圖片
應該是還不至於影響到使用體驗,scroll反而是live,所以當使用者狂點卷軸到最下方.很容易網頁就崩壞
設置時間還可以防止這個問題,想問一下老師還有什麼地方可以改善!

2021-05-07 08:43 UTC, cwpeng commented
第三週的版面有比較好哦，大致上還 OK。

剩下第二週的捲動到底部繼續載入下一頁景點資料的部份還沒完成，就請完成之後再和我說 ~

2021-05-07 08:50 UTC, cwpeng commented
我幫你用不同的螢幕測試看起來是可以了，不過建議你的偵測可以再寬一點，例如 < 650 之類的，有些螢幕的高度比較高，會沒有辦法偵測到滑動到底部的狀況。

setInterval 確實可以解決這個問題，會一點點 delay 也還可以接受。使用 scroll 也有辦法可以阻擋連續觸發，同時沒有 delay 的狀況。不過是 OK 的。

就請你重新再發一個 Review 的請求給我，我才能幫你 Approve，還有幾天的時間，可以再試著把細節處理得更好。

2021-05-08 08:54 UTC, kxkfkqk commented
老師我這個請求是不是要先刪掉?
上次衝突不知道是不是這個原因造成的
還有突然發現我上線的網站,隔一段時間就會抓不到資料了
進去就會變成我預設的資料錯誤,但是重開就又好了
請問這是怎麼回事呢

2021-05-08 16:25 UTC, cwpeng commented
不用刪掉 Pull Request，直接在這個 Pull Request 的右上方重新發 Review Request 給我就好。

那是資料庫的連線閒置八小時後會自動斷開，確實只要重新開啟伺服器就會恢復，之後有額外的空閒可以利用 Connection Pool 這個技巧來處理這個細節問題。

2021-05-09 13:53 UTC, cwpeng approved these changes
OK.

2021-05-09 14:05 UTC, merged